***  These error messages are defined
***  by Editor Toolbox

040  File too big! File not read
042  Bad Command line -
043  Error while deleting backup file
044  File buffer almost full, exit now
045  Search string not found -
050  Filename:

***  These error messages are copied
***  from the Turbo Pascal Reference
***  Manual's list of I/O errors

001  New file
002  File not found
003  Path not found
004  Too many files open
005  File access denied
006  Invalid file handle
007  Memory control blocks destroyed
008  Insufficient memory
009  Invalid memory block address
010  Invalid environment
011  Invalid format
012  Invalid access code
015  Invalid drive number
016  Cannot remove current directory
017  Cannot rename across drives
019  Disk write protected
020  Unknown unit ID
021  Drive not ready
023  Disk data error
027  Disc sector not found
028  Printer out of paper
029  Write error
030  Read error
031  General failure
032  File sharing violation
033  File locking violation
034  Improper disk change
080  File already exists
100  Disk read error
101  Disk write error
102  File not assigned
103  File not open
104  File is not open for input
105  File is not open for output
106  Invalid numeric format
255  Unable to read/write to drive

***  These error messages are defined
***  by Compiler

201  Identifier already declared
202  LHS of assignment must be a variable
203  -> not expected
204  Token expected here was
205  Type error
220  Error Position
250  Assembler Error
251  Run time error

011  TEXT     colour of text characters
048  COMMAND  colour of command line characters
========================================================================
***  Key definitions and Help Message
***     These will appear in the help message in the reverse order
***     to that shown here

***     Columns 1..3 are the key number used when calling the command  from the
***       keyboard. If they are 000 then the command can only be entered from a
***       command line
***     Column 5 is the command letter as it would appear on a command line.
***       lower case letters represent internal command numbers (a=1, b=2, ...)
***       for commands which cannot be entered from a command line
***     Columns 6 onwards are comments for use in the help message

236 ?    Alt-f5 Repeat last Find/Subs
000
235 k    Alt-f4 Learn Macro
000
234 j    Alt-f3 Directory
000
233 {    Alt-f2 Outdent line
000 Oxxx        Compiler options = xxx
232 }    Alt-f1 Indent line
000 Rxxx        Read file xxx
000 A           Ask 'Continue (Y/N)'
000 I/xxx/      Insert xxx
027 U    Esc    Undo
000    (u: ignore case, a: ask)
013 N    Ret    Newline
000 Sua/xxx/yy/ Subs. yyy for xxx
009 C    Tab    Copy undo
000 Fu/xxx/     Find xxx
008 B    BS     Delete left
000
210 g    Ins    Insert Line
196 E    f10    Bottom of file
211 .    Del    Delete right
195 a    f9     Do command
209 V    Pg Dn  Page down
194 i    f8     Compile and run
201 ^    Pg Up  Page up
193 h    f7     Compile
205 >    ->     Char right
192 d    f6     Quit
203 <    <-     Char left
191 c    f5     Repeat
208 +    Dn     Line down
190 b    f4     Save file
200 -    Up     Line up
189 Z    f3     Delete to eol
207 ]    End    End of  line
188 T    f2     Top of File
199 [    Home   Beginning of line
187 D    f1     Delete line
000
000
000
000                                Commands
000
000
